### PR TITLE
Migrate Android plugins API

### PR DESCRIPTION
**Pull request by willlockwood**
/domain @samandmoore @Betterment/flutter-platform 
/platform @samandmoore @Betterment/android-platform 

Migrated the plugin to the android v2 embedding. I had in a previous comment, some confusion about how to handle the new task activity flag; after looking into that a while ago, it seems clear that keeping it the way it is here makes the most sense.

https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

### CODE REVIEW

**Comment by samandmoore** [comment]
looks good. so, you decided to remove the v1 style. i'm cool with that. if we wanna upstream this (which would be great), we should see if they're cool with dropping support for the v1 style.

**Comment by willlockwood** [comment]
Hey @samandmoore; I realized that I'm not completely clear about what you're describing here as the "v1 style" (other than just the fact that we're using the v2 embedding, which is the main purpose here). And similarly, after looking back at the droibit repo: 
1) I'm not very optimistic that this repo will get updated any time soon (seems very, very loosely maintained), and 
2) I'm not sure how I would really clarify whether they're cool with these changes, without just creating a PR, no?

**Comment by willlockwood** [comment]
nanda

**Comment by samandmoore** [comment]
I think it would make sense to open a PR to them. 

And for the v1 style, I meant that based on the docs it appears possible to do the new embedding style and the old one so that the project could work with versions of flutter that don't support the new style yet. But I think those are very old versions at this point.

**Comment by samandmoore** [comment]
<<domainlgtm

**Pull request closed without merging**
